name: chaii
channels:
  - huggingface
  - conda-forge
dependencies:
  - black=21.8b0
  - flake8=3.9.2
  - isort=5.9.3
  - mypy=0.910
  - numpy=1.21.2
  - pre-commit=2.15.0
  - python=3.8.10
  - pytorch=1.9.0
  - transformers=4.9.2
