[tool.isort]
profile = "black"

[tool.black]
line-length = 88

[tool.pylint.messages_control]
disable = [
    "no-member",
    "too-many-arguments",
    "too-few-public-methods",
    "no-else-return",
    "duplicate-code",
    "consider-using-with",
    "unspecified-encoding",
    "too-many-branches",
    "too-many-locals",
    "pointless-string-statement",
    "redefined-builtin",
    "dangerous-default-value",
]

[tool.pylint.format]
max-line-length = 88

[[tool.mypy.overrides]]
module = [
    'src.*',
    'pandas',
    'sklearn.model_selection',
]
ignore_missing_imports = true

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = [
    "ignore::DeprecationWarning",
	"ignore::UserWarning"
]
